export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SHOW_RESULT = "SHOW_RESULT";


export const SHOW_ALERT = "SHOW_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const SHOW_FORM_USER_INFO = "SHOW_FORM_USER_INFO";
export const SHOW_FORM_BOT_INFO = "SHOW_FORM_BOT_INFO";
export const SHOW_NOTIFICATION_FORM = "SHOW_NOTIFICATION_FORM";
export const SEND_FORM_USER_INFO = "SEND_FORM_USER_INFO";
export const SEND_FORM_BOT_INFO = "SEND_FORM_BOT_INFO";
